### ISSUE TITLE
Compatibility with node-sass cli

### ISSUE THREAD

**Issue by ackerdev** [idcware/node-sass-jspm-importer#3]
The node-sass cli offers options for custom importers and functions from .js files, like so:
```
node-sass input.scss output.css --importer custom_importer.js --functions custom_functions.js
```

The importer must have the importer function as it's default export.

Put simply: If you split your index.js up into `importer.js` and `functions.js`, you will gain compatibility with the node-sass cli (functions.js is probably not ready to go because of the path_prefix closure, but importer would be ready as it is). The only thing I'm unsure about is if there are any convenient methods to expose this to users, like any convenient methods to get the path to these from npm.

**Comment by Gu1** [comment]
Hello Nicholas,
I did not know that node-sass exposed this on its CLI interface.
I'm gonna put the importer & functions in two source files.
