### ISSUE TITLE
jspm_resolve() helper returns relative path

### ISSUE THREAD

**Issue by adiachenko** [idcware/node-sass-jspm-importer#8]
I am not entirely sure that this is an issue worth fixing but when using node-sass-jspm-importer in my project I ended up prepending forward slash to the result of jspm_resolve execution.
```
$fa-font-path: "/" + jspm_resolve("font-awesome/fonts");
@import "jspm:font-awesome/scss/font-awesome";
```
Otherwise it will try to resolve paths with an assumption that compiled sass will be located directly under document root ('/') and break in other cases (i.e. '/css' will resolve to 'css/jspm_packages/npm/font-awesome') in the above example when not prepending forward slash.

**Comment by Gu1** [comment]
What did you pass as argument to sassJspm.resolve_function ? It's the prefix used for paths returned by jspm_resolve in your sass code.

**Comment by adiachenko** [comment]
Yeah, my bad.) I used relative path in my gulp file. Thx for the tip.
