### ISSUE TITLE
Path resolve against .ts

### ISSUE THREAD

**Issue by vadimpopa** [idcware/node-sass-jspm-importer#9]
Can you adjust that line to work against .ts also
```javascript
filePath = path.resolve(fromFileURL(filePath).replace(/\.js$/, ''));
```
Want to try your plugin on typescript dev env. Thanks.

**Comment by vadimpopa** [comment]
I've pushed a PR for that. I have other issue now, not sure yet what might be the reason, maybe you could give me some hints.

```javascript
Error: app/app.scss
Error: media query expression must begin with '('
        on line 25 of stdin
>> @import "jspm:ionic/dist/src/scss/ionic"
   ----------------------------------------^
```

**Comment by Gu1** [comment]
I have no idea. Could it be a syntax error in your sass file ?..

**Comment by vadimpopa** [comment]
Yes, it's on my sass file, but as you can see above, it was on the line where the plugin should resolve the path. Anyways I've managed it by writing my plugin in a few lines for that and didn't get any sass errors.
